### ISSUE TITLE
This extension interferes with VectorStorage

### ISSUE THREAD

**Issue by Metalhead33** [artisticMink/anlatan-nai-extras#27]
When I have this extension turned on, VectorStorage fails to function at all. When I have it turned off, it functions as intended.

**Comment by artisticMink** [comment]
The extension is outdated since NAI's Erato release and shouldn't be used with the current version of SillyTavern. I have to add a warning in the README. 

ST's Advanced Formatting can be used as a replacement for Chat Format Window, disabling 'Always add character's name to prompt ' makes it function similar to NAI Extra's 'chat mode'. 

There's no native replacement right now for Adventure Mode.
